server:
  port: 8044
  servlet:
    context-path: /fund-service
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: fund-service
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource:
    durid00username: sa
    durid00password: sa
    druid00jdbcUrl: jdbc:h2:/Users/allen/studyspace/projects/multidatasource/src/main/resources/fund;USER=sa;PASSWORD=sa;
    durid00driverClass: org.h2.Driver

    durid01username: sa
    durid01password: sa
    druid01jdbcUrl: jdbc:h2:/Users/allen/studyspace/projects/multidatasource/src/main/resources/fund;USER=sa;PASSWORD=sa;
    durid01driverClass: org.h2.Driver

    durid02username: sa
    durid02password: sa
    druid02jdbcUrl: jdbc:h2:/Users/allen/studyspace/projects/multidatasource/src/main/resources/fund;USER=sa;PASSWORD=sa;
    durid02driverClass: org.h2.Driver


mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: cn.allen.multidatasource.fund.entity
  configuration:
    map-underscore-to-camel-case: true


allen:
  dsroutingset:
    dataSourceNum: 3
    tableNum: 4
    routingField: "fundCode"
    tableSuffixStyle: "%04d"
    tableSuffixConnect: "_"
    routingStrategy: "ROUTING_DS_TABLE_STRATEGY"